-file("/usr/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(pattern_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/pattern_lexer.xrl", 88).

strip(TokenChars, TokenLen) -> lists:sublist(TokenChars, 2, TokenLen - 2).

-file("/usr/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/pattern_lexer.erl", 309).
yystate() -> 160.

yystate(167, [108|Ics], Line, Tlen, _, _) ->
    yystate(161, Ics, Line, Tlen+1, 38, Tlen);
yystate(167, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(167, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(167, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(167, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(167, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(167, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,167};
yystate(166, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(162, Ics, Line, Tlen+1, Action, Alen);
yystate(166, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,166};
yystate(165, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(163, Ics, Line, Tlen+1, Action, Alen);
yystate(165, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(165, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,165};
yystate(164, [32|Ics], Line, Tlen, _, _) ->
    yystate(164, Ics, Line, Tlen+1, 40, Tlen);
yystate(164, [13|Ics], Line, Tlen, _, _) ->
    yystate(164, Ics, Line, Tlen+1, 40, Tlen);
yystate(164, [9|Ics], Line, Tlen, _, _) ->
    yystate(164, Ics, Line, Tlen+1, 40, Tlen);
yystate(164, [10|Ics], Line, Tlen, _, _) ->
    yystate(164, Ics, Line+1, Tlen+1, 40, Tlen);
yystate(164, Ics, Line, Tlen, _, _) ->
    {40,Tlen,Ics,Line,164};
yystate(163, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(155, Ics, Line, Tlen+1, Action, Alen);
yystate(163, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,163};
yystate(162, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(161, [115|Ics], Line, Tlen, _, _) ->
    yystate(136, Ics, Line, Tlen+1, 38, Tlen);
yystate(161, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(161, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(161, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(161, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(161, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(161, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,161};
yystate(160, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(152, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(127, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(159, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(149, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [87|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(154, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(165, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(116, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(140, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(140, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(148, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(164, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(164, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(164, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(164, Ics, Line+1, Tlen+1, Action, Alen);
yystate(160, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [C|Ics], Line, Tlen, Action, Alen) when C >= 99, C =< 101 ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [C|Ics], Line, Tlen, Action, Alen) when C >= 105, C =< 115 ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(160, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(160, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,160};
yystate(159, [97|Ics], Line, Tlen, _, _) ->
    yystate(167, Ics, Line, Tlen+1, 38, Tlen);
yystate(159, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(159, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(159, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(159, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(159, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,159};
yystate(158, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(166, Ics, Line, Tlen+1, Action, Alen);
yystate(158, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,158};
yystate(157, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(156, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(155, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(147, Ics, Line, Tlen+1, Action, Alen);
yystate(155, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,155};
yystate(154, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(146, Ics, Line, Tlen+1, Action, Alen);
yystate(154, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,154};
yystate(153, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(152, [114|Ics], Line, Tlen, _, _) ->
    yystate(144, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, [39|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, [34|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(152, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,152};
yystate(151, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(150, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(158, Ics, Line, Tlen+1, Action, Alen);
yystate(150, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,150};
yystate(149, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(149, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(149, [39|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 38, Tlen);
yystate(149, [34|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 38, Tlen);
yystate(149, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(149, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(149, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,149};
yystate(148, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(156, Ics, Line, Tlen+1, Action, Alen);
yystate(148, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,148};
yystate(147, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(139, Ics, Line, Tlen+1, Action, Alen);
yystate(147, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,147};
yystate(146, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(146, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,146};
yystate(145, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(153, Ics, Line, Tlen+1, Action, Alen);
yystate(145, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,145};
yystate(144, [117|Ics], Line, Tlen, _, _) ->
    yystate(136, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,144};
yystate(143, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(135, Ics, Line, Tlen+1, Action, Alen);
yystate(143, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(135, Ics, Line, Tlen+1, Action, Alen);
yystate(143, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(135, Ics, Line, Tlen+1, Action, Alen);
yystate(143, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,143};
yystate(142, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(150, Ics, Line, Tlen+1, Action, Alen);
yystate(142, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,142};
yystate(141, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 57 ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(141, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,141};
yystate(140, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(124, Ics, Line, Tlen+1, Action, Alen);
yystate(140, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(132, Ics, Line, Tlen+1, Action, Alen);
yystate(140, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(140, Ics, Line+1, Tlen+1, Action, Alen);
yystate(140, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(140, Ics, Line, Tlen+1, Action, Alen);
yystate(140, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(140, Ics, Line, Tlen+1, Action, Alen);
yystate(140, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(140, Ics, Line, Tlen+1, Action, Alen);
yystate(140, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(140, Ics, Line, Tlen+1, Action, Alen);
yystate(140, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,140};
yystate(139, [87|Ics], Line, Tlen, Action, Alen) ->
    yystate(131, Ics, Line, Tlen+1, Action, Alen);
yystate(139, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,139};
yystate(138, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(130, Ics, Line, Tlen+1, Action, Alen);
yystate(138, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,138};
yystate(137, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(145, Ics, Line, Tlen+1, Action, Alen);
yystate(137, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,137};
yystate(136, [101|Ics], Line, Tlen, _, _) ->
    yystate(128, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,136};
yystate(135, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(151, Ics, Line, Tlen+1, Action, Alen);
yystate(135, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(151, Ics, Line, Tlen+1, Action, Alen);
yystate(135, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(143, Ics, Line, Tlen+1, Action, Alen);
yystate(135, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(143, Ics, Line, Tlen+1, Action, Alen);
yystate(135, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(143, Ics, Line, Tlen+1, Action, Alen);
yystate(135, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,135};
yystate(134, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(142, Ics, Line, Tlen+1, Action, Alen);
yystate(134, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,134};
yystate(133, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(125, Ics, Line, Tlen+1, Action, Alen);
yystate(133, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,133};
yystate(132, [39|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 35, Tlen);
yystate(132, [34|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 35, Tlen);
yystate(132, [10|Ics], Line, Tlen, _, _) ->
    yystate(140, Ics, Line+1, Tlen+1, 35, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(140, Ics, Line, Tlen+1, 35, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(140, Ics, Line, Tlen+1, 35, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(140, Ics, Line, Tlen+1, 35, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 40 ->
    yystate(140, Ics, Line, Tlen+1, 35, Tlen);
yystate(132, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,132};
yystate(131, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(131, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,131};
yystate(130, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(122, Ics, Line, Tlen+1, Action, Alen);
yystate(130, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,130};
yystate(129, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(137, Ics, Line, Tlen+1, Action, Alen);
yystate(129, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,129};
yystate(128, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 36, Tlen);
yystate(128, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 36, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 36, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 36, Tlen);
yystate(128, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,128};
yystate(127, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(127, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(127, [39|Ics], Line, Tlen, _, _) ->
    yystate(135, Ics, Line, Tlen+1, 38, Tlen);
yystate(127, [34|Ics], Line, Tlen, _, _) ->
    yystate(135, Ics, Line, Tlen+1, 38, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(127, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,127};
yystate(126, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(125, [52|Ics], Line, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Tlen+1, Action, Alen);
yystate(125, [51|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(125, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(125, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,125};
yystate(124, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(123, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(115, Ics, Line, Tlen+1, Action, Alen);
yystate(123, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,123};
yystate(122, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(114, Ics, Line, Tlen+1, Action, Alen);
yystate(122, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,122};
yystate(121, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(120, [95|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,120};
yystate(119, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(119, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,119};
yystate(118, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(126, Ics, Line, Tlen+1, Action, Alen);
yystate(118, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,118};
yystate(117, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(117, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,117};
yystate(116, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(115, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(115, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,115};
yystate(114, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(114, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,114};
yystate(113, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(121, Ics, Line, Tlen+1, Action, Alen);
yystate(113, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,113};
yystate(112, [95|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 39, Tlen);
yystate(112, [45|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 39, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(112, Ics, Line, Tlen+1, 39, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(112, Ics, Line, Tlen+1, 39, Tlen);
yystate(112, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line,112};
yystate(111, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(111, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,111};
yystate(110, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(118, Ics, Line, Tlen+1, Action, Alen);
yystate(110, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,110};
yystate(109, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 57 ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(109, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,109};
yystate(108, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(107, [89|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(107, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,107};
yystate(106, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(105, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(105, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,105};
yystate(104, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(104, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,104};
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(103, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,103};
yystate(102, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(101, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(100, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(99, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(98, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(98, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,98};
yystate(97, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Tlen+1, Action, Alen);
yystate(97, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,97};
yystate(96, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(96, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,96};
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(94, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,94};
yystate(93, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(93, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,93};
yystate(92, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(92, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,92};
yystate(91, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(91, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,91};
yystate(90, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(89, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [52|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(110, Ics, Line, Tlen+1, Action, Alen);
yystate(86, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,86};
yystate(85, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(83, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(83, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,83};
yystate(82, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(82, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,82};
yystate(81, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(81, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(81, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,81};
yystate(80, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, [90|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(134, Ics, Line, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,78};
yystate(77, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(129, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [46|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 43, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line,76};
yystate(75, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(75, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,75};
yystate(74, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(69, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(69, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,69};
yystate(68, [46|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 2, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(66, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(65, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(119, Ics, Line, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line};
yystate(62, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(62, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,62};
yystate(61, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 43 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 50 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(157, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [42|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 41, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(60, Ics, Line, Tlen+1, 41, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 41 ->
    yystate(60, Ics, Line, Tlen+1, 41, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 43 ->
    yystate(60, Ics, Line, Tlen+1, 41, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,52};
yystate(51, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(48, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [90|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(44, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(42, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(40, [51|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,40};
yystate(39, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(37, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,37};
yystate(36, [11|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 42, Tlen);
yystate(36, [12|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 42, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(36, Ics, Line, Tlen+1, 42, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 14 ->
    yystate(36, Ics, Line, Tlen+1, 42, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line,36};
yystate(35, [61|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 6, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,35};
yystate(34, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(33, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,33};
yystate(32, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [54|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(26, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, 32, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,20};
yystate(19, [61|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 3, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,19};
yystate(18, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(11, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(10, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(9, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 51 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(5, [75|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(3, [62|Ics], Line, Tlen, _, _) ->
    yystate(156, Ics, Line, Tlen+1, 5, Tlen);
yystate(3, [61|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 5, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,3};
yystate(2, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, TokenLine) ->
    yyaction_30(TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLen, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLen, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLen, TokenLine);
yyaction(36, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars, TokenLine);
yyaction(37, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLen, TokenLine);
yyaction(38, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_38(TokenChars, TokenLine);
yyaction(39, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_39(TokenChars, TokenLine);
yyaction(40, _, _, _) ->
    yyaction_40();
yyaction(41, _, _, _) ->
    yyaction_41();
yyaction(42, _, _, _) ->
    yyaction_42();
yyaction(43, _, _, _) ->
    yyaction_43();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/pattern_lexer.xrl", 28).
yyaction_0(TokenLine) ->
     { token, { wildcard, TokenLine } } .

-compile({inline,yyaction_1/1}).
-file("src/pattern_lexer.xrl", 29).
yyaction_1(TokenLine) ->
     { token, { comma, TokenLine } } .

-compile({inline,yyaction_2/1}).
-file("src/pattern_lexer.xrl", 30).
yyaction_2(TokenLine) ->
     { token, { dot, TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("src/pattern_lexer.xrl", 31).
yyaction_3(TokenLine) ->
     { token, { equal_to, TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("src/pattern_lexer.xrl", 32).
yyaction_4(TokenLine) ->
     { token, { not_equal, TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("src/pattern_lexer.xrl", 33).
yyaction_5(TokenLine) ->
     { token, { less_than, TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("src/pattern_lexer.xrl", 34).
yyaction_6(TokenLine) ->
     { token, { greater_than, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("src/pattern_lexer.xrl", 35).
yyaction_7(TokenLine) ->
     { token, { less_than_or_equal_to, TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("src/pattern_lexer.xrl", 36).
yyaction_8(TokenLine) ->
     { token, { greater_than_or_equal_to, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/pattern_lexer.xrl", 37).
yyaction_9(TokenLine) ->
     { token, { colon, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("src/pattern_lexer.xrl", 38).
yyaction_10(TokenLine) ->
     { token, { left_bracket, TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("src/pattern_lexer.xrl", 39).
yyaction_11(TokenLine) ->
     { token, { right_bracket, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/pattern_lexer.xrl", 40).
yyaction_12(TokenLine) ->
     { token, { left_parenthesis, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("src/pattern_lexer.xrl", 41).
yyaction_13(TokenLine) ->
     { token, { right_parenthesis, TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("src/pattern_lexer.xrl", 42).
yyaction_14(TokenLine) ->
     { token, { and_cond, TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("src/pattern_lexer.xrl", 43).
yyaction_15(TokenLine) ->
     { token, { or_cond, TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("src/pattern_lexer.xrl", 44).
yyaction_16(TokenLine) ->
     { token, { not_cond, TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("src/pattern_lexer.xrl", 45).
yyaction_17(TokenLine) ->
     { token, { followed_by, TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("src/pattern_lexer.xrl", 46).
yyaction_18(TokenLine) ->
     { token, { like, TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("src/pattern_lexer.xrl", 47).
yyaction_19(TokenLine) ->
     { token, { matches, TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("src/pattern_lexer.xrl", 48).
yyaction_20(TokenLine) ->
     { token, { is_superset, TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("src/pattern_lexer.xrl", 49).
yyaction_21(TokenLine) ->
     { token, { is_subset, TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("src/pattern_lexer.xrl", 50).
yyaction_22(TokenLine) ->
     { token, { last, TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("src/pattern_lexer.xrl", 51).
yyaction_23(TokenLine) ->
     { token, { contained_in, TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("src/pattern_lexer.xrl", 52).
yyaction_24(TokenLine) ->
     { token, { start, TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("src/pattern_lexer.xrl", 53).
yyaction_25(TokenLine) ->
     { token, { stop, TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("src/pattern_lexer.xrl", 54).
yyaction_26(TokenLine) ->
     { token, { seconds, TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("src/pattern_lexer.xrl", 55).
yyaction_27(TokenLine) ->
     { token, { true, TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("src/pattern_lexer.xrl", 56).
yyaction_28(TokenLine) ->
     { token, { false, TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("src/pattern_lexer.xrl", 57).
yyaction_29(TokenLine) ->
     { token, { within, TokenLine } } .

-compile({inline,yyaction_30/1}).
-file("src/pattern_lexer.xrl", 58).
yyaction_30(TokenLine) ->
     { token, { repeats, TokenLine } } .

-compile({inline,yyaction_31/1}).
-file("src/pattern_lexer.xrl", 59).
yyaction_31(TokenLine) ->
     { token, { times, TokenLine } } .

-compile({inline,yyaction_32/2}).
-file("src/pattern_lexer.xrl", 61).
yyaction_32(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_33/3}).
-file("src/pattern_lexer.xrl", 63).
yyaction_33(TokenChars, TokenLen, TokenLine) ->
     S = strip (TokenChars, TokenLen),
     { token, { hex, TokenLine, S } } .

-compile({inline,yyaction_34/3}).
-file("src/pattern_lexer.xrl", 66).
yyaction_34(TokenChars, TokenLen, TokenLine) ->
     S = strip (TokenChars, TokenLen), { token, { binary, TokenLine, S } } .

-compile({inline,yyaction_35/3}).
-file("src/pattern_lexer.xrl", 69).
yyaction_35(TokenChars, TokenLen, TokenLine) ->
     S = strip (TokenChars, TokenLen),
     { token, { string, TokenLine, S } } .

-compile({inline,yyaction_36/2}).
-file("src/pattern_lexer.xrl", 72).
yyaction_36(TokenChars, TokenLine) ->
     { token, { boolean, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_37/3}).
-file("src/pattern_lexer.xrl", 75).
yyaction_37(TokenChars, TokenLen, TokenLine) ->
     S = strip (TokenChars, TokenLen),
     { token, { timestamp, TokenLine, S } } .

-compile({inline,yyaction_38/2}).
-file("src/pattern_lexer.xrl", 78).
yyaction_38(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, TokenChars } } .

-compile({inline,yyaction_39/2}).
-file("src/pattern_lexer.xrl", 79).
yyaction_39(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, TokenChars } } .

-compile({inline,yyaction_40/0}).
-file("src/pattern_lexer.xrl", 81).
yyaction_40() ->
     skip_token .

-compile({inline,yyaction_41/0}).
-file("src/pattern_lexer.xrl", 82).
yyaction_41() ->
     skip_token .

-compile({inline,yyaction_42/0}).
-file("src/pattern_lexer.xrl", 83).
yyaction_42() ->
     skip_token .

-compile({inline,yyaction_43/0}).
-file("src/pattern_lexer.xrl", 84).
yyaction_43() ->
     { error, syntax } .

-file("/usr/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 313).
